// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:87cfe175-6574-4491-981d-c611458e05e9",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_0Lpq98Jnz",
    "aws_user_pools_web_client_id": "4r4b78e9nnr78qjpno97pqp3rj"
};


export default awsmobile;
